core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from home import views as home_views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


# Fallback view for the main domain
def home(request):
    return HttpResponse("Main Site - Bildung")


urlpatterns = [
    path('admin/', admin.site.urls),
    path("forums/", include("forums.urls")),
    path("chat/", include("chat.urls")),

    # Main site root
    path('', home_views.guest_home, name='guest_home'),

    # Include all user-related routes (signup, login, dashboards)
    path("users", include("users.urls")),
    path('courses/', include('courses.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # For password reset and other auth views
    ]

SUBDOMAIN_URLCONFS = {
    'instructor': 'courses.instructor_urls',
    'student': 'courses.student_urls',  # you'll create later
}

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views
from users import views as user_views

app_name = 'courses'

urlpatterns = [
    # Public
    path('', views.course_list, name='course_list'),

    # Student URLs
    path('student/dashboard/', user_views.student_dashboard, name='student_dashboard'),
    path('student/courses/', views.browse_courses, name='browse_courses'),
    path('student/enroll/<int:course_id>/', views.enroll_course, name='enroll_in_course'),
    path('student/course/<int:course_id>/', views.student_course_detail, name='student_course_detail'),
    path('lecture/<int:lecture_id>/complete/', views.mark_lecture_complete, name='mark_lecture_complete'),
    
    #instructor
    path('dashboard/', views.instructor_dashboard, name='instructor_dashboard'),
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("courses/", include("courses.urls")),  # general course views
    path("instructor/", include("courses.instructor_urls", namespace="instructor")),  # instructor dashboard & management
    path("quizzes/", include("quizzes.urls")),
    # User-related routes
    path('', include('users.urls')),

    # Student section URLs
    path('student/', include(('users.student_urls', 'student'), namespace='student')),

    # Student course-related routes
    path('student/', include(('courses.student_urls', 'student_courses'), namespace='student_courses')),
]

courses/forms.py
from django import forms
from django.utils.text import slugify
from .models import Course, Lecture, Feedback, Enrollment, Module
from django.forms import inlineformset_factory


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'description', 'price']
        widgets = {'description': forms.Textarea(attrs={'rows': 4})}

class ModuleForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = ['title', 'description']

class LectureForm(forms.ModelForm):
    class Meta:
        model = Lecture
        fields = ['title', 'video', 'file']


ModuleFormSet = inlineformset_factory(Course, Module, form=ModuleForm, extra=1, can_delete=True)
LectureFormSet = inlineformset_factory(Module, Lecture, form=LectureForm, extra=1, can_delete=True)

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Write feedback here...'}),
        }

    def __init__(self, *args, **kwargs):
        course = kwargs.pop('course', None)  # passed from view
        super().__init__(*args, **kwargs)
        if course:
            # restrict feedback to enrolled students
            enrolled_students = Enrollment.objects.filter(course=course).values_list("student", flat=True)
            self.fields['student'].queryset = course.students.filter(id__in=enrolled_students)

courses/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.dateparse import parse_datetime

from .models import Course, Enrollment, Lecture, LectureProgress, Feedback, CourseEvent, Module
from .forms import CourseForm, LectureForm, FeedbackForm, ModuleFormSet
from users.decorators import instructor_required
from django.db.models import Q

# -------------------------------
# Common Views
# -------------------------------


def course_list(request):
    query = request.GET.get('q')
    courses = Course.objects.all()

    if query:
        courses = courses.filter(
            Q(title__icontains=query) | Q(description__icontains=query)
        )

    return render(request, 'courses/course_list.html', {'courses': courses, 'query': query})

@login_required(login_url='/login/')
def browse_courses(request):
    """Student: browse unenrolled courses"""
    if getattr(request.user, 'role', None) != 'student':
        return redirect('login')

    available_courses = Course.objects.exclude(students=request.user)
    return render(request, 'courses/browse_course.html', {'courses': available_courses})


# -------------------------------
# Student Views
# -------------------------------

@login_required(login_url='/login/')
def enroll_course(request, course_id):
    """Student: enroll in a course"""
    if getattr(request.user, 'role', None) != 'student':
        return redirect('login')

    course = get_object_or_404(Course, id=course_id)
    Enrollment.objects.get_or_create(student=request.user, course=course)
    messages.success(request, f"Enrolled in {course.title}")
    return redirect('student_dashboard')


@login_required(login_url='/login/')
def student_course_detail(request, course_id):
    """Student: view course details + progress"""
    course = get_object_or_404(Course, id=course_id, students=request.user)
    for module in course.modules.all():
      lectures = module.lectures.all()

    total = lectures.count()
    completed = LectureProgress.objects.filter(
        student=request.user, lecture__in=lectures, completed=True
    ).count()

    progress_map = {
        lp.lecture_id: lp.completed
        for lp in LectureProgress.objects.filter(student=request.user, lecture__in=lectures)
    }

    return render(request, 'courses/student_course_detail.html', {
        'course': course,
        'lectures': lectures,
        'total': total,
        'completed': completed,
        'progress_map': progress_map
    })


@login_required(login_url='/login/')
def mark_lecture_complete(request, lecture_id):
    """Student: mark lecture complete"""
    lecture = get_object_or_404(Lecture, id=lecture_id)
    course = lecture.course

    if getattr(request.user, 'role', None) != 'student':
        return redirect('login')

    LectureProgress.objects.get_or_create(
        student=request.user,
        lecture=lecture,
        defaults={'completed': True}
    )
    return redirect('student_course_detail', course_id=course.id)


# -------------------------------
# Instructor Views
# -------------------------------

@login_required
def instructor_dashboard(request):
    """Instructor dashboard"""
    courses = Course.objects.filter(instructor=request.user)
    return render(request, 'courses/instructor/home.html', {'courses': courses})

@login_required
def add_course(request):
    if request.method == 'POST':
        course_form = CourseForm(request.POST, request.FILES)
        if course_form.is_valid():
            course = course_form.save(commit=False)
            course.instructor = request.user
            course.save()

            module_total = int(request.POST.get('modules-TOTAL_FORMS', 0))
            for i in range(module_total):
                title = request.POST.get(f'modules-{i}-title')
                desc = request.POST.get(f'modules-{i}-description')
                if title:
                    module = Module.objects.create(course=course, title=title, description=desc)

                    lecture_index = 0
                    while True:
                        lecture_title = request.POST.get(f'modules-{i}-lectures-{lecture_index}-title')
                        lecture_file = request.FILES.get(f'modules-{i}-lectures-{lecture_index}-video')
                        if not lecture_title:
                            break
                        Lecture.objects.create(module=module, title=lecture_title, video=lecture_file)
                        lecture_index += 1

            return redirect('instructor_dashboard')
    else:
        course_form = CourseForm()
        module_formset = ModuleFormSet()

    context = {'course_form': course_form, 'module_formset': module_formset}
    return render(request, 'courses/instructor/add_course.html', context)


@login_required
def course_edit(request, course_id):
    """Instructor: edit existing course"""
    course = get_object_or_404(Course, id=course_id, instructor=request.user)
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES, instance=course)
        if form.is_valid():
            form.save()
            messages.success(request, "Course updated successfully.")
            return redirect('instructor_dashboard')
    else:
        form = CourseForm(instance=course)
    return render(request, 'courses/instructor/course_edit.html', {'form': form, 'course': course})


@login_required
def course_detail(request, course_id):
    course = get_object_or_404(Course, id=course_id, instructor=request.user)
    modules = course.modules.all()
    lectures = []
    for module in course.modules.all():
        lectures = module.lectures.all()

    return render(request, 'courses/instructor/course_detail.html', {
        'course': course,
        'modules': modules,
        'lectures': lectures,
    })

@login_required
def add_lecture(request, course_id):
    course = get_object_or_404(Course, id=course_id, instructor=request.user)
    if request.method == 'POST':
        form = LectureForm(request.POST, request.FILES)
        if form.is_valid():
            lecture = form.save(commit=False)
            lecture.course = course
            lecture.save()
            messages.success(request, "Lecture added successfully.")
            return redirect('instructor:course_detail', course_id=course.id)
    else:
        form = LectureForm()
    return render(request, 'courses/instructor/add_lecture.html', {'form': form, 'course': course})



@login_required
def edit_lecture(request, course_id, lecture_id):
    lecture = get_object_or_404(Lecture, id=lecture_id, course__id=course_id, course__instructor=request.user)
    if request.method == "POST":
        form = LectureForm(request.POST, request.FILES, instance=lecture)
        if form.is_valid():
            form.save()
            messages.success(request, "Lecture updated successfully.")
            return redirect('instructor:course_detail', course_id=course_id)
    else:
        form = LectureForm(instance=lecture)
    return render(request, 'courses/instructor/edit_lecture.html', {'form': form, 'course_id': course_id})


@login_required
def delete_lecture(request, course_id, lecture_id):
    lecture = get_object_or_404(Lecture, id=lecture_id, course__id=course_id, course__instructor=request.user)
    if request.method == "POST":
        lecture.delete()
        messages.success(request, "Lecture deleted successfully.")
        return redirect('instructor:course_detail', course_id=course_id)
    return render(request, 'courses/instructor/delete_lecture.html', {'lecture': lecture, 'course_id': course_id})


@login_required
def course_progress_report(request, course_id):
    course = get_object_or_404(Course, id=course_id, instructor=request.user)
    enrollments = Enrollment.objects.filter(course=course)
    progress_data = []
    total_lectures = sum(module.lectures.count() for module in course.modules.all())

    for enrollment in enrollments:
        student = enrollment.student
        completed = LectureProgress.objects.filter(student=student, lecture__course=course, completed=True).count()
        progress = (completed / total_lectures * 100) if total_lectures else 0
        progress_data.append({"student": student, "completed": completed, "total": total_lectures, "progress": progress})

    return render(request, 'courses/instructor/course_progress_report.html', {'course': course, 'progress_data': progress_data})


@login_required
def add_event(request, course_id):
    course = get_object_or_404(Course, id=course_id, instructor=request.user)
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        start_time = parse_datetime(request.POST.get('start_time'))
        end_time = parse_datetime(request.POST.get('end_time'))

        CourseEvent.objects.create(course=course, title=title, description=description, start_time=start_time, end_time=end_time)
        messages.success(request, "Event added successfully.")
        return redirect('instructor:course_detail', course_id=course.id)

    return render(request, 'courses/instructor/add_event.html', {'course': course})



@login_required
def give_feedback(request, course_id):
    course = get_object_or_404(Course, id=course_id, instructor=request.user)

    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.instructor = request.user
            feedback.course = course
            feedback.save()
            messages.success(request, "Feedback submitted successfully!")

courses/templates/courses/access_denied.html
{% extends "base.html" %}
{% block content %}
<h2>Access Denied</h2>
<p>You must enroll in <strong>{{ course.title }}</strong> before you can view its lectures.</p>
<a href="{% url 'enroll_course' course.id %}">Enroll Now</a>
{% endblock %}

courses/templates/courses/browse_course.html
{% extends "base.html" %}
{% block content %}
<h2>Available Courses</h2>

<ul>
    {% for course in courses %}
        <li>
            <strong>{{ course.title }}</strong> - {{ course.description }} <br>
            Price: ${{ course.price }} <br>
            <a href="{% url 'enroll_in_course' course.id %}">Enroll</a>
        </li>
    {% empty %}
        <li>No new courses available to enroll.</li>
    {% endfor %}
</ul>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "base.html" %}
{% block content %}
<h2>Search Results for "{{ query }}"</h2>

{% for course in courses %}
    <div class="card">
        <h5>{{ course.title }}</h5>
        <p>{{ course.description }}</p>
        <a href="{% url 'instructor:course_detail' course.id %}" class="btn btn-primary">View Course</a>
            {% if user.is_authenticated and user.role == 'student' %}
                <a href="{% url 'enroll_course' course.id %}">Enroll</a>
            {% endif %}


    </div>
{% empty %}
    <p>No courses found.</p>
{% endfor %}

{% endblock %}

courses/templates/courses/instructor_course_detail.html
{% extends "base.html" %}
{% block content %}
<h2>{{ course.title }}</h2>
<p>{{ course.description }}</p>

<h3>Your Lectures</h3>
<ul>
    {% for lecture in course.lectures.all %}
        <li>{{ lecture.title }}</li>
    {% empty %}
        <li>No lectures yet.</li>
    {% endfor %}
</ul>

<h3>Feedbacks Given</h3>
<ul>
    {% for feedback in course.feedbacks.all %}
        <li>
            To: {{ feedback.student.username }} <br>
            {{ feedback.text }} <br>
            <small>{{ feedback.created_at }}</small>
        </li>
    {% empty %}
        <li>No feedback given yet.</li>
    {% endfor %}
</ul>


<a href="{% url 'add_lecture' course.id %}">+ Add Lecture</a> |
<a href="{% url 'give_feedback' course.id %}">Give Feedback</a>
{% endblock %}

courses/templates/courses/instructor_dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
    <h2>Instructor Dashboard</h2>
    <p>Welcome, {{ request.user.username }}!</p>

    <h3>Your Courses</h3>
    <a href="{% url 'create_course' %}" class="btn btn-primary mb-3">+ Add New Course</a>

    {% if courses %}
        <ul class="list-group">
            {% for course in courses %}
                <li class="list-group-item">
                    <strong>{{ course.title }}</strong> <br>
                    {{ course.description|truncatewords:20 }}
                    <div class="mt-2">
                        <a href="{% url 'manage_course' course.id %}" class="btn btn-sm btn-secondary">Manage</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You have not created any courses yet.</p>
    {% endif %}
</div>
{% endblock %}

courses/templates/courses/student_course_detail.html
{% extends "base.html" %}
{% block content %}
<h2>{{ course.title }}</h2>
<p>{{ course.description }}</p>

{% if total > 0 %}
    <p>Progress: {{ completed }}/{{ total }} lectures completed</p>
    <progress value="{{ completed }}" max="{{ total }}"></progress>
{% endif %}

<h3>Lectures</h3>
<ul>
    {% for lecture in lectures %}
        <li>
            <strong>{{ lecture.title }}</strong>
            {% if progress_map|default:{}|dict_has_key:lecture.id %}
                ✅ Completed
            {% else %}
                <a href="{% url 'mark_lecture_complete' lecture.id %}">Mark as Complete</a>
            {% endif %}
        </li>
    {% endfor %}
</ul>

<h3>Upcoming Events</h3>
<ul>
    {% for event in course.events.all %}
        <li>
            <strong>{{ event.title }}</strong> <br>
            {{ event.start_time }} - {{ event.end_time }} <br>
            {{ event.description }}
        </li>
    {% empty %}
        <li>No upcoming events</li>
    {% endfor %}
</ul>
{% endblock %}

courses/templates/courses/student_dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
  <h2>Welcome, {{ request.user.username }} 👋</h2>
  <hr>
  <h4>Your Enrolled Courses</h4>

  {% if enrollments %}
  <div class="row">
    {% for e in enrollments %}
      <div class="col-md-4 mb-3">
        <div class="card shadow-sm">
          <div class="card-body">
            <h5 class="card-title">{{ e.course.title }}</h5>
            <p class="card-text">{{ e.course.description|truncatewords:20 }}</p>
            <a href="{% url 'student_courses:student_course_detail' e.course.id %}" class="btn btn-primary btn-sm">View Details</a>
            <a href="{% url 'student_courses:mark_lecture_complete' e.course.id %}" class="btn btn-outline-secondary btn-sm">Progress</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% else %}
  <p>You haven't enrolled in any courses yet.</p>
  <a href="{% url 'student_courses:browse_courses' %}" class="btn btn-success">Browse Courses</a>
  {% endif %}
</div>
{% endblock %}